[project]
name = "fastapi-prac2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncpg>=0.31.0",
    "dotenv>=0.9.9",
    "fastapi>=0.128.0",
    "psycopg>=3.3.2",
    "sqlalchemy>=2.0.45",
    "uvicorn>=0.40.0",
]
